name: auto-merge-dependabot
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
permissions:
  contents: write
  pull-requests: write
jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: fastify/github-action-merge-dependabot@v3
        if: |
          contains('version-update:semver-minor,version-update:semver-patch,security-update', steps.meta.outputs.update-type)
        with:
          target: minor
