name: Release
on:
  push:
    branches: [master]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          check-latest: true
          cache: npm

      - name: Upgrade npm to v11
        run: |
          npm -v
          npm i -g npm@^11
          npm -v

      - name: Install dependencies
        run: npm ci --no-audit --fund=false --include=dev

      - name: Release
        run: npx -y semantic-release@24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
